### ISSUE TITLE
generating checkpoint tours function

### ISSUE THREAD

**Issue by Zhiar43** [MohammedSalahadin/falcon#24]
this is the return of the function = c3ff This property's ID before conditions -> 1 This property's ID after first condition -> 1 This property's ID Before Generate ->  This property's ID After Generate -> 1result2 is empty: SELECT * FROM falcon.property_tours_has_property_checkpoints where property_tours_id = '1';Array
(
)

`public function generateCheckpointTours()
    {
        if ($this->id < 1) {
            echo " The id has not been generated yet ";
            return false;
        }
        $query = "SELECT id FROM falcon.property_tours where id = '$this->id';";
        $tours = (new Execute($query, "multiQuery"))->result;
        foreach ($tours as $tour) {
            $tourID = $tour["id"];
            $tourObj = new Tours();
            if ($tourObj->generate($tourID)) {
                $this->checkPointTours[$tourID] = $tourObj;
            }
            unset($tourObj);
        }
    }`

**Comment by MohammedSalahadin** [comment]
Tour class function generate doesn't have any problems.
To test it separately you can use the following code:
```
//generating a new tour
$tour = new Tour();
if($tour->generate('10')){
    echo $tour->id;
    echo $tour->tourName;
}
```
I investigated in that and I figured out  That you are accessing the database in the wrong way, instead of :
```$query = "SELECT id FROM falcon.property_tours where id = '$this->id';";```
So change it to look like this```SELECT id FROM falcon.property_tours where property_id = '$this->id';```
Because you will access all the tours for specific property.. 
so Basically here is the fix of your code including the validation 

```
function generateCheckpointTours()
{
    if ($this->id < 1) { echo " The id has not been generated yet "; return false; }
    $query = "SELECT id FROM falcon.property_tours where property_id = '$this->id';";
    $tours = (new Execute($query, "multiQuery"))->result;
    // print_r($tours);
    if (!empty($tours)) { // Checking is impoortant
        foreach ($tours as $tour) {
            $tourID = $tour["id"];
            $tourObj = new Tours();
            if ($tourObj->generate($tourID)) {
                $this->checkPointTours[$tourID] = $tourObj;
                echo "checkpoint Tour $tourObj->id name: $tourObj->tourName is created!";
            }
            unset($tourObj);
        }
        return true;//
    } else {
        //do nothing, looks like this propery doesn't have any checkpoint tours
        return true;
    }
}
```

**Comment by Zhiar43** [comment]
Thank you Mohammed, i see the problem NOW ofc (:

**Comment by MohammedSalahadin** [comment]
You are welcome, anytime you face any type of any error post it here immediately.
